name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
         - linux/arm64
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
    
    # https://docs.docker.com/build/ci/github-actions/multi-platform/
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
      
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd gromox-core && docker buildx build . --file Dockerfile --platform linux/arm64 --tag gromox-core:$(date +%s)
