name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd gromox-core && docker buildx build . --file Dockerfile --platform linux/arm64 --tag gromox-core:$(date +%s)
